name: Deploy to File Manager

on:
  push:
    branches:
      - main # หรือ master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy directly to File Manager
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/ # ใช้เครื่องหมาย / ได้เลย เพราะเราตั้ง FTP ให้ชี้ตรงเข้าโฟลเดอร์ปลายทางแล้ว
          exclude: |
            **/.git*
            **/.git*/**
            config/db.php
